# Generated by Django 3.1.4 on 2020-12-16 09:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('casemgmt', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caseloadrole',
            name='groups',
        ),
        migrations.AddField(
            model_name='caseloadrole',
            name='groups',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='caseload_roles', to='auth.group'),
        ),
        migrations.RemoveField(
            model_name='caseloadrole',
            name='users',
        ),
        migrations.AddField(
            model_name='caseloadrole',
            name='users',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='caseload_roles', to=settings.AUTH_USER_MODEL),
        ),
    ]
