# Generated by Django 3.1.4 on 2020-12-16 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('casemgmt', '0002_auto_20201216_0925'),
    ]

    operations = [
        migrations.RenameField(
            model_name='caseloadrole',
            old_name='groups',
            new_name='group',
        ),
        migrations.RenameField(
            model_name='caseloadrole',
            old_name='users',
            new_name='user',
        ),
    ]
