# Generated by Django 3.1.5 on 2021-01-19 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('casemgmt', '0003_auto_20201216_0941'),
    ]

    operations = [
        migrations.CreateModel(
            name='WkcmpEligibilityData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_monthly_income', models.DecimalField(decimal_places=2, max_digits=8)),
                ('employer', models.CharField(max_length=100)),
                ('num_dependents', models.PositiveSmallIntegerField()),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wkcmp_eligibility', to='casemgmt.document')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
