# Generated by Django 2.2.22 on 2021-08-02 20:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('casemgmt', '0004_wkcmpeligibilitydata'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentActivityLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('verb', models.CharField(choices=[('Viewed', 'Viewed document'), ('Created', 'Created document'), ('Updated', 'Updated document'), ('Deleted', 'Deleted document'), ('Shared', 'Shared document'), ('Mailed', 'Mailed document')], max_length=10)),
                ('description', models.CharField(max_length=255, null=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_activities', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='casemgmt.Document')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
